name: mewayz
description: "Mewayz - All-in-One Business Platform for social media management, CRM, e-commerce, and more"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.2
  
  # Image handling
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  
  # Responsive design
  sizer: ^2.0.15
  
  # Storage & persistence
  shared_preferences: ^2.2.2
  
  # Networking
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  
  # Data visualization
  fl_chart: ^0.65.0
  
  # UI enhancement
  fluttertoast: ^8.2.4
  pull_to_refresh: ^2.0.0
  
  # Typography
  google_fonts: ^6.1.0
  
  # Internationalization
  intl: ^0.19.0

  # File handling
  file_picker: ^8.1.2

  # Authentication and Database
  supabase_flutter: ^2.8.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.3
  
  # Additional dependencies for professional mobile app
  web: any
  url_launcher: ^6.2.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  
  # Biometric authentication
  local_auth: ^2.1.8
  
  # QR Code generation
  qr_flutter: ^4.1.0
  
  # Email validation
  email_validator: ^2.1.17
  
  # OTP input
  pin_code_fields: ^8.0.1
  
  # Image picker
  image_picker: ^1.0.7
  
  # Network state management
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # App icons and launch images are automatically generated
  # by the flutter_launcher_icons package
  
  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  
  # The following section is specific to Flutter packages.
  # https://flutter.dev/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages